### ISSUE TITLE
[Feature] Homescreen stack widgets

### ISSUE THREAD

**Issue by Crunchbits** [zacharee/LockscreenWidgets#26]
Hello, first of all I wanted to say that this is a really great app.

Perhaps this is out of the scopes for this app, but I realized something recently. The lockscreen widgets features allows multiple widgets by swiping left and right which is effectively stacked widgets. For homescreen/launchers this is a feature limited to iOS and a few Android OEMs. I think that, if possible, it would be really neat for the app to allow the stacked widgets feature that it already has but as a homescreen widget. It would offer the unique ability to expand this feature to many phones/launchers that don't support stack widgets.

One limitation I might see would be the launcher's limitation for widgets to take left/right swipes on widgets as inputs, but I think this could be fixed by making it an up/down swipe to change widgets. This would function sort of like a pseudo-scroll up/down since scrolling up/down is possible for widgets on pretty much any android phone launcher.

Again, I think this would be a useful extension to the app since it already has a bit of that functionality built up. But those are just my two cents.

**Comment by BroJac5246** [comment]
I would absolutely love to see this. It's almost certainly out of the scope of this app, but I'd still use it!

**Comment by jonrok** [comment]
+1!!
 We've all been hoping the new Nova release would have stackable widgets but sadly the didn't do it maybe you should collaborate with them teach them how to code 🔥🤣 kidding of course Nova is the shit ✊

**Comment by zacharee** [comment]
Proxying widgets through another widget isn't really possible to do, unfortunately.

**Comment by Lorestan00** [comment]
I would echo the other views. Would be great to have a stackable widgets on the home screen. 

Action Launcher, Samsung OneUI and Niagara Launcher have it. Does it need a launcher to enable such a feature ?

**Comment by zacharee** [comment]
Widgets aren't like normal view layouts in Android. They use a different system for remotely defining layouts that a widget host can then instantiate. That means the app providing a widget has no direct control over how that widget is actually displayed or created. Launchers can show widgets in stacks if they want because they have direct control over the view hierarchy and can instantiate and group widget layouts.

Actions performed on the widgets are sent back to their respective providers to perform any logic and request any layout updates. There's just too much separation of logic for a widget proxy to be practical.
